### ISSUE TITLE
TVirtualTextControl parsing Simple HTML

### ISSUE THREAD

**Issue by jonahzheng** [vdisasm/FMXTestSynedit#1]
If TVirtualTextControl can  parsing Simple HTML，
because TWebbrowser Can't be cover component, Such as a button

**Comment by vdisasm** [comment]
I'd like to point that this project is just example of syntax highlighting done with FMX. It should not be used in any serious work.

If you mean if it can parse HTML, basically original SynEdit HTML unit can be used, but this project won't be supported/updated.
